name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: for OUTPUT in $(find . -name "Dockerfile"); do IMAGE_TAG=$(echo docker.pkg.github.com/tsickert/dockerfiles/$(cut -d/ -f2 <<< "$OUTPUT"):$(date +%s)) && docker build -t $IMAGE_TAG -f $OUTPUT . && docker push $IMAGE_TAG; done;
