name: Test Login

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker login https://docker.pkg.github.com -u tsickert -p ${{ secrets.GITHUB_TOKEN }}
